const quizActionTypes = {
    FETCH_QUIZES_REQUEST: 'FETCH_QUIZES_REQUEST',
    FETCH_QUIZES_SUCCESS: 'FETCH_QUIZES_SUCCESS',
    FETCH_QUIZES_FAILURE: 'FETCH_QUIZES_FAILURE',
    FETCH_QUESTIONS_REQUEST: 'FETCH_QUESTIONS_REQUEST',
    FETCH_QUESTIONS_SUCCESS: 'FETCH_QUESTIONS_SUCCESS',
    FETCH_QUESTIONS_FAILURE: 'FETCH_QUESTIONS_FAILURE',
  };
  
  export default quizActionTypes;